### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by katacarbix** [MaxLeiter/Drift#12]
I designed a basic logo inspired by snowdrifts and the (mostly) achromatic theme of the web client:

![drift](https://user-images.githubusercontent.com/1340784/157369593-1dd22e9a-5eaf-4775-bd8f-df5bdfc41d60.png)

Let me know what you think!

**Comment by MaxLeiter** [comment]
I think this is great! I'll need to try it in the client for a bit before deciding for sure but it's a good starting point at the very least

**Comment by MaxLeiter** [comment]
Hey @katacarbix, are you able to export the logo to SVG?

**Comment by katacarbix** [comment]
Yes, I have it right here:

https://user-images.githubusercontent.com/1340784/157532175-07aa9c98-79b4-4d22-a0e8-761f87332abc.svg

Would you like me to open another PR?

**Comment by katacarbix** [comment]
Sorry that one looks weird because I kept the source strokes in a hidden layer. Here's an optimized one with the logo how you see it above:

https://user-images.githubusercontent.com/1340784/157534046-b832be44-9f67-4003-8eae-d4bff32ead9e.svg

**Comment by MaxLeiter** [comment]
A pull request would be great
