### ISSUE TITLE
Setup and requirements

### ISSUE THREAD

**Issue by craftzneko** [MaxLeiter/Drift#138]
This prehaps doesnt fit into an issue except prehaps as an update to documentation.

I am missing some basic understanding of how to implement this. I think it would help understanding what is required before using this project. For example i assume i need a github location for the gists to be stored in? What does the postgres database do? Is there anybody that has a quickstart guide to go from nothing to a working instance

**Comment by MaxLeiter** [comment]
Hey @pr1malc0de, thanks for the issue.

Drift is still a work in progress, but you can use it now if you follow the README and are willing to mess around a bit. 

Drift doesn't use gist in any way -- the DB is for hosting your snippets and code. The database stores users, posts, API tokens, etc. If you'd like to help write a quickstart guide let me know and I'd be happy to help you get started.

**Comment by craftzneko** [comment]
Thanks @MaxLeiter

I think I was thrown by the env variable settings for GitHub, but I see now that its for using GitHub as an identity provider. I would be happy to help with a Quickstart. Im learning as I go so will need to be corrected, but as I try to get this running I will make notes and let you know!

**Comment by MaxLeiter** [comment]
@pr1malc0de best of luck. I've just pushed a `.env.default` that should help you get started
