### ISSUE TITLE
Current Docker Compose

### ISSUE THREAD

**Issue by potter-jason** [MaxLeiter/Drift#140]
Is there a latest/greatest way to install via docker/ docker-compose? I attempted to use the docker-compose currently posted and I got an error about the .server :+1: 

unable to prepare context: path "./server" not found

Please let me know what the best way to install as this project looks perfect

**Comment by MaxLeiter** [comment]
There are some issues with using Docker at the moment, but @kinghat's progress is available in https://github.com/MaxLeiter/Drift/pull/135
