### ISSUE TITLE
Logout and Theme does not work

### ISSUE THREAD

**Issue by qwertzdenek** [MaxLeiter/Drift#143]
**Describe the bug**
Logout and Theme Buttons on top does not work.

**To Reproduce**
Steps to reproduce the Theme behavior:
1. Click Theme
2. Click Theme again
3. Nothing happens

Steps to reproduce the Logout behavior:
1. Login by any method
2. You still see only Login button even if you are logged in
3. Logout not possible

**Expected behavior**
Theme should be toggled and persisted for next visit.

Similar for logged in users, Logout button should be there.

**Comment by MaxLeiter** [comment]
Thanks, I made a mistake doing some refactoring. Should fix tonight

**Comment by MaxLeiter** [comment]
Closed by d0a73a7
