### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by qwertzdenek** [MaxLeiter/Drift#144]
**Describe the bug**
Production build using `pnpm build` fails on linter errors (on refactor branch).

```
Failed to compile.

./src/app/components/badges/created-ago-badge/index.tsx
6:10  Error: 'useMemo' is defined but never used.  @typescript-eslint/no-unused-vars
10:8  Warning: The 'createdDate' object construction makes the dependencies of useEffect Hook (at line 19) change on every render. To fix this, wrap the initialization of 'createdDate' in its own useMemo() Hook.  react-hooks/exhaustive-deps

./src/app/components/header/buttons.tsx
3:10  Error: 'useSelectedLayoutSegment' is defined but never used.  @typescript-eslint/no-unused-vars
```

**Environment**

- pnpm 7.29.1
- node.js v18.15.0

**Expected behavior**
Build is possible without errors and code smells.

Thank you ;)

**Comment by cxplay** [comment]
The same problem was encountered.

**Comment by MaxLeiter** [comment]
Sorry these are pretty easy fixes if someone wants to submit a pull request. I can't work on drift for the next ~week.

**Comment by qwertzdenek** [comment]
https://github.com/MaxLeiter/Drift/pull/145
