### ISSUE TITLE
Posts should be server-side generated

### ISSUE THREAD

**Issue by MaxLeiter** [MaxLeiter/Drift#22]
Should be do-able with getStaticProps.

**Comment by icepaq** [comment]
I was taking a look into this task. The way you are storing the auth token is going to be problematic when using getServerSideProps. Local storage is only available on the client side. 

So prior to rendering posts on the server side, we'll need to store `drift-token` in a cookie.

https://github.com/vercel/next.js/discussions/16824

**Comment by MaxLeiter** [comment]
Hm yeah that makes sense @icepaq. Is that something you're down to tackle? It shouldn't be too hard to replace use of localStorage w a cookie

**Comment by icepaq** [comment]
@MaxLeiter  sure!

I'll get to that soon.

**Comment by icepaq** [comment]
@MaxLeiter 

I'm working on this right now and don't see any issue with rendering private posts on the server side as well. Is there any reason you only specified public and unlisted?

The drift-token is now accessible on the server side since I made the cookie change.

**Comment by MaxLeiter** [comment]
Nope, now that we use the cookie we can do private posts too 👍
