### ISSUE TITLE
Add denylist for invalid JWT tokens

### ISSUE THREAD

**Issue by MaxLeiter** [MaxLeiter/Drift#25]
When a user logs out we should add the JWT token to a table and add checks against it in the jwt middleware so it can't be used by a third party.

**Comment by spykelion** [comment]
If I get this right, there should be a collection of user-sessions being monitored. If a user logs out of the system, the token should be added to the expired or used token collection(based on the collection name). 
Don't know if I've grasp it right. An new to this.

**Comment by spykelion** [comment]
Wow, I almost got it. I will see how to handle the session use case if permitted

**Comment by MaxLeiter** [comment]
@spykelion great! let me know if I can be of any help. I found https://dev.to/chukwutosin_/how-to-invalidate-a-jwt-using-a-blacklist-28dl, which may be helpful for you.

**Comment by spykelion** [comment]
Okay, great

**Comment by MaxLeiter** [comment]
@spykelion are you working on this? Otherwise I was planning to tackle it this weekend. Let me know if I can be of help

**Comment by spykelion** [comment]
Probably will need help in setting the local env.

**Comment by MaxLeiter** [comment]
Sounds good. The README has been updated so it should get you setup environment wise, I tried to keep it fairly straight forward.

**Comment by spykelion** [comment]
Just to be clear. I should add a signout route.
I hope this doesn't affect the existing functionality of the application

**Comment by MaxLeiter** [comment]
sorry @spykelion, saw your comment and forgot. What problem are you experiencing? You probably need to add a migration, you can use `npx sequelize-cli migration:generate --name add-denylist-table` from the `server` folder to have a file created for you in `server/src/migrations`. Then you can add add the table there as well, https://medium.com/@andrewoons/how-to-define-sequelize-associations-using-migrations-de4333bf75a7 may be of help. Then run `yarn migrate` to run the migration and modify your DB.

**Comment by MaxLeiter** [comment]
@spykelion I’ve reworked with the database a little bit locally and will push soon, it should make the process for writing a migration more clear

**Comment by spykelion** [comment]
Thanks sir

**Comment by spykelion** [comment]
Same error message after running the above command.
`npx sequelize-cli migration:generate --name add-denylist-table`
`yarn migrate`

**Comment by MaxLeiter** [comment]
@spykelion I pushed the reworked migrations. Add a file in `server/src/migrations` with the proper fields from the Model file and you should be set. In your case it looks like you just forgot to add a `token` column

**Comment by MaxLeiter** [comment]
@spykelion can you open a PR? That will make it easier for me to work with you on it

**Comment by spykelion** [comment]
Okay. I also pulled.

**Comment by spykelion** [comment]
I get this when I run `yarn migrate`
_yarn run v1.22.18
$ sequelize-cli-ts db:migrate_

_Sequelize CLI [Node: 16.14.2, CLI: 5.5.2, ORM: 6.17.0]_


_ERROR: Cannot find "/home/user/Drift/server/config/config.js". 
Have you run "sequelize init"?_

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by MaxLeiter** [comment]
Ah sorry, the process changed in the refactor. Migrations will now automatically apply when you start the server, and you have to programmatically undo them until I add a nicer wrapper. See https://github.com/sequelize/umzug#reverting-executed-migration and  https://github.com/MaxLeiter/Drift/blob/main/server/src/database.ts#L19-L44

**Comment by spykelion** [comment]
After running `yarn run dev`
Registration password required: false
Error: Cannot find module '/home/user/Drift/server/src/lib/models/../../../config/config.js'
Require stack:
- /home/user/Drift/server/src/lib/models/index.js
- /home/user/Drift/server/node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize-service.js
- /home/user/Drift/server/node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize.js
- /home/user/Drift/server/node_modules/sequelize-typescript/dist/index.js
- /home/user/Drift/server/src/lib/models/User.ts
- /home/user/Drift/server/src/routes/auth.ts
- /home/user/Drift/server/src/routes/index.ts
- /home/user/Drift/server/src/app.ts
- /home/user/Drift/server/src/server.ts
- /home/user/Drift/server/index.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (/home/user/Drift/server/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._resolveFilename (/home/user/Drift/server/node_modules/tsconfig-paths/src/register.ts:90:36)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/user/Drift/server/src/lib/models/index.js:8:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/Drift/server/src/lib/models/index.js',
    '/home/user/Drift/server/node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize-service.js',
    '/home/user/Drift/server/node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize.js',
    '/home/user/Drift/server/node_modules/sequelize-typescript/dist/index.js',
    '/home/user/Drift/server/src/lib/models/User.ts',
    '/home/user/Drift/server/src/routes/auth.ts',
    '/home/user/Drift/server/src/routes/index.ts',
    '/home/user/Drift/server/src/app.ts',
    '/home/user/Drift/server/src/server.ts',
    '/home/user/Drift/server/index.ts'
  ]
}

**Comment by MaxLeiter** [comment]
did you run `yarn` in `server`?

**Comment by spykelion** [comment]
yes I did

**Comment by MaxLeiter** [comment]
I pushed a change that may fix it; we don't need config.js anymore. Not sure why yarn dev works for me though.

You should see

```bash
yarn run v1.22.17
$ NODE_ENV=development nodemon index.ts
[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node index.ts`
Registration password required: false
Database path: /Users/maxleiter/Documents/drift/drift.sqlite
Checking migrations...
(node:91547) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log
(Use `node --trace-deprecation ...` to show where the warning was created)
Server running on port 3000
```

**Comment by spykelion** [comment]
when /signout route is executed
Executing (default): INSERT INTO `JWTDenyLists` (`id`,`token`,`createdAt`,`updatedAt`) VALUES ($1,$2,$3,$4);
Request POST /auth/signout failed: Error
    at Database.<anonymous> (/home/user/Drift/server/node_modules/sequelize/src/dialects/sqlite/query.js:227:27)
    at /home/user/Drift/server/node_modules/sequelize/src/dialects/sqlite/query.js:225:50
    at new Promise (<anonymous>)
    at Query.run (/home/user/Drift/server/node_modules/sequelize/src/dialects/sqlite/query.js:225:12)
    at /home/user/Drift/server/node_modules/sequelize/src/sequelize.js:643:28
    at async SQLiteQueryInterface.insert (/home/user/Drift/server/node_modules/sequelize/src/dialects/abstract/query-interface.js:773:21)
    at async JWTDenyList.save (/home/user/Drift/server/node_modules/sequelize/src/model.js:4046:35)

**Comment by MaxLeiter** [comment]
Let's move this discussion to the PR
