### ISSUE TITLE
Move design framework

### ISSUE THREAD

**Issue by MaxLeiter** [MaxLeiter/Drift#3]
geist-ui is great for prototyping, but heavily reliant on JS and not very customizable.

**Comment by sampaioxsamuel** [comment]
Hey, do you got any library in mind? I have some but I was thinking if you got prototype, wireframe or something else, so we can choose what could be better

**Comment by MaxLeiter** [comment]
I envisioned trying to stay pretty close to what we have now, just with less JS. What do you have in mind? I'm open to ideas

**Comment by sampaioxsamuel** [comment]
by less JS you mean using pure sass/css? if so theres always styled components.
I was thinking about [chakra](https://chakra-ui.com/) or [radix](https://www.radix-ui.com/), the last one its good if we build our own design system but I don't if this is something that we should worry now :)

**Comment by MaxLeiter** [comment]
Yeah, I've heard good things about radix from an accessibility point. And yes, I do mean pure CSS (I'd rather avoid an extra build step if possible) with JS for progressive enhancement. For example, tabs don't render at all with JS disabled right now. We could also try upstreaming to geist-ui, but I think we'll use few enough components it'll still be maintainable to have our own. styled-components sounds good, I just went with CSS modules because that's what I'm used to.

**Comment by sampaioxsamuel** [comment]
Yeah I can look up on this and test if I find a good option

**Comment by MaxLeiter** [comment]
That'd be great! Thanks @sampaioxsamuel  🙏

**Comment by maxall41** [comment]
Maybe take a look at https://www.cirrus-ui.com/

**Comment by lordvins226** [comment]
Maybe Chakra or Mantine can be nice choice.

**Comment by XeroxDev** [comment]
I can also recommend bulma, tailwind or (css only) bootstrap.

**Comment by MaxLeiter** [comment]
Finished by switching to radix-ui and custom styling
