### ISSUE TITLE
Bad padding at bottom of page when creating post

### ISSUE THREAD

**Issue by MaxLeiter** [MaxLeiter/Drift#30]
**Describe the bug**
From reddit:

Looks really good!

One thing, which should be a quick fix: When you are creating a new gist, the dropdown on the submit button will overflow outside of the viewport (so you have to scroll down after opening it). I would just add some extra padding to the bottom, or alternatively scroll down automatically when you open it.

**Comment by lordvins226** [comment]
<img width="395" alt="Capture d’écran 2022-03-15 à 19 49 56" src="https://user-images.githubusercontent.com/39868202/158459701-1efa5668-3638-4069-a71a-23af3b499164.png">
This issue ?
