### ISSUE TITLE
Store Token and User ID as a Cookie

### ISSUE THREAD

**Issue by icepaq** [MaxLeiter/Drift#31]
As discussed in issue #22 storing tokens in localstorage becomes a problem when trying to retrieve them on the server side.

Will just set token and userid Cookies for now just to make testing easier.

**Comment by MaxLeiter** [comment]
We dont need to store the userid on the client anymore, that was before I stored it in the JWT iirc

**Comment by icepaq** [comment]
I tried removing the drift-userid cookie and was having issues creating a new post. I'll just leave it in there for now.
