### ISSUE TITLE
Private posts are actually unlisted

### ISSUE THREAD

**Issue by icepaq** [MaxLeiter/Drift#35]
**Describe the bug**
You can view private posts is if they are unlisted.

**To Reproduce**
1. Create a private post and copy the link
2. Open private browsing or another browser and go to the link.
3. You will see the post.

**Expected behavior**
You shouldn't see the post

**Comment by emilyst** [comment]
Maybe "private" is not the best choice of terminology. I think "unlisted" or "secret" (this latter being [used by Gist](https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists)) might be better.

I totally get the confusion—the meaning of "private" could easily be conflated with its meaning for GitHub repositories (which require auth to access).

**Comment by emilyst** [comment]
Actually, disregard my comment, I might have gotten confused over the intention of "private."

**Comment by MaxLeiter** [comment]
I intended (and didn't put much thought into it) to have 4 categories of posts:

1) Public (indexable, listed on eventual user pages)
2) Unlisted (non-indexable, not listed anywhere public, etc.)
3) Private (requires user auth)
4) Password (requires password and no auth).

I'm open to better terminology

Did you try this with the cookie PR? It occurs in master atm because localStorage persists in private browsing.

**Comment by emilyst** [comment]
> I intended (and didn't put much thought into it) to have 4 categories of posts:
> 
> 1. Public (indexable, listed on eventual user pages)
> 2. Unlisted (non-indexable, not listed anywhere public, etc.)
> 3. Private (requires user auth)
> 4. Password (requires password and no auth).
> 
> I'm open to better terminology

Honestly, this feels crystal clear to me. I was simply mistaken about the subject of this issue.

**Comment by icepaq** [comment]
> Did you try this with the cookie PR? It occurs in master atm because localStorage persists in private browsing.

I believe the cookie PR is already merged. No?

**Comment by icepaq** [comment]
Either way, I think that there should be some backend authentication to make sure that the session cookie is actually valid and is allowed to access the private post.

**Comment by MaxLeiter** [comment]
oh yeah my bad, vacation brain. Do you want to include a fix in #34 or leave it for (yourself or someone else) later? I'd prefer it in this PR, but understandable if you don't want to address it.

**Comment by icepaq** [comment]
Probably best to do it in a separate PR. Just for organization.

**Comment by icepaq** [comment]
@MaxLeiter Is there a way to match a session ID to a username?

**Comment by MaxLeiter** [comment]
Do you mean the JWT? The user ID is included in it, see https://github.com/MaxLeiter/Drift/blob/208ba42/server/lib/middleware/jwt.ts#L22

**Comment by icepaq** [comment]
Probably won't get to this for another few days. If anyone comes across this issue and wants to take it, feel free. Just @ me so I know it's been taken.

I'll delete this comment when I start working on this, if it hasn't been taken by then.

**Comment by MaxLeiter** [comment]
Is this still a problem? Try visiting https://paste.maxleiter.com/post/private/5eb504ec-5ba8-47da-a21e-daa08d0e981f
