### ISSUE TITLE
List public gists on homepage

### ISSUE THREAD

**Issue by MaxLeiter** [MaxLeiter/Drift#4]

**Comment by sampaioxsamuel** [comment]
Hey if I understand this correctly you want to show all public gists on the homepage even if the user is not loggin?

**Comment by MaxLeiter** [comment]
@sampaioxsamuel that was my intention, yes. I'm not married to the idea, but I liked the idea of posts being discoverable. Maybe user pages are a better option.

**Comment by sampaioxsamuel** [comment]
I like too but I'm thinking on the homepage with only a small preview and the features listed, and add a new tab like you say discovery and there list all users public gists

**Comment by nickelswitte** [comment]
I would love to use this feature as well, as I'd like to use Drift as a little markdown blog :)
