### ISSUE TITLE
Paginate your post list

### ISSUE THREAD

**Issue by MaxLeiter** [MaxLeiter/Drift#45]

**Comment by icepaq** [comment]
Should paginations be a single page app? By that I mean load an entire array of posts then use a hook to display 1-10, 11 - 20...

**Comment by MaxLeiter** [comment]
I tried working on this recently (and pushed the result) and that's what I did. https://github.com/MaxLeiter/Drift/blob/main/client/components/post-list/index.tsx#L104-L108
