### ISSUE TITLE
Client: better client-side validation when publishing a post

### ISSUE THREAD

**Issue by gekoke** [MaxLeiter/Drift#46]
The following is based only on the demo server at https://drift.maxleiter.com/, so disregard if the most recent builds do not display this behavior.

Currently, if the client's request to create a post is met with a 403 (such as when the title is blank or the post contains no files), the client shows no indication of this and the submit button stalls in a loading animation.

Consider handling this case gracefully, perhaps even duplicating the validation on the client's side to highlight required fields in real time. 

![image](https://user-images.githubusercontent.com/63151928/160365784-768a2f2e-9481-4b27-9cdf-1ce0de6e094e.png)

**Comment by MaxLeiter** [comment]
This has been fixed, but leaving it open because we could have better client-side validation.
