### ISSUE TITLE
Client: real-time syntax highlighting

### ISSUE THREAD

**Issue by gekoke** [MaxLeiter/Drift#47]
GitHub Gists offers syntax highlighting inferred from the filename while modifying the text in the editor, which leads to a considerably nicer experience compared to having a separate tab for previews. Only when the filename ends in .md, do they render the preview tab.

Perhaps implementing something similar should be considered for this project as well. I realize this would not be trivial, as the syntax highlighting seems to take place on the server side at the moment.

**Comment by MaxLeiter** [comment]
This happens now, try changing the filename (markdown is implied)
