### ISSUE TITLE
Client: Display which fields are causing an Internal Server Error

### ISSUE THREAD

**Issue by jorgediazjr** [MaxLeiter/Drift#53]
<img width="1423" alt="drift_500" src="https://user-images.githubusercontent.com/32808705/160671388-dff5144a-30a4-47f1-867a-afc2d0653b32.png">
Issue:

When creating a new post https://drift.maxleiter.com/new, a missing filename results in an **Internal Server Error** but there is no clear indication letting me know that is the reason.

It took me a few seconds to notice that was why and then I was able to create the post. Though that may not be the case with other users.

Suggestions:
It would be nice if a field with missing input would be styled with `border: 1px solid #F00;` and/or a popover letting the user know that a missing input is preventing the post from being created.

<img width="1295" alt="drift_possible_fix" src="https://user-images.githubusercontent.com/32808705/160673642-5e2ef9f0-7617-43fd-b34d-6e5931150cf0.png">

Another possible feature could be adding a succinct message in the red bubble,
e.g.: **Internal Server Error: Enter filename**

**Comment by MaxLeiter** [comment]
Thanks for the issue. The borders are a good idea. Interestingly I can’t replicate the internal server error locally, only when it’s hosted, but server logs show it’s being handled.

**Comment by MaxLeiter** [comment]
Didn't get around to highlighting but fixed the problem; in production 500 errors are stripped and I wasn't manually returning 4xx's. Thanks!

**Comment by jorgediazjr** [comment]
Ah okay, glad it's fixed!
