### ISSUE TITLE
Dark mode client flash effect when opening on the browser

### ISSUE THREAD

**Issue by Bakhtiyar-Garashov** [MaxLeiter/Drift#55]
**Describe the bug**

A flash effect (quick transition to black from white) happens when opening the client in browser

**To Reproduce**
1. Open in dark mode
2. Reload page multiple times

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - MacOs Monterey 12.3
 - Chrome
 - Version 99.0.4844.83 (Official Build) (x86_64)

**Additional context**

**Comment by MaxLeiter** [comment]
Thanks for the report. I believe this is an issue with geist-ui, so either we'll need to upstream a fix or go with #3
