### ISSUE TITLE
WELCOME_CONTENT is overly escaped in the demo

### ISSUE THREAD

**Issue by jazcarate** [MaxLeiter/Drift#67]
**Describe the bug**
In the demo page (https://drift.maxleiter.com/) the welcome content (set by `WELCOME_CONTENT` env 

**To Reproduce**
1. Go to the demo site
2. ![image](https://user-images.githubusercontent.com/403456/161377367-7a3310e9-ccc1-415d-a4e2-7cd820c34889.png)

**Expected behavior**
The welcome content looks good

**Comment by MaxLeiter** [comment]
Not a bug with drift, just a problem with the demos env. Fixed, thanks!
