### ISSUE TITLE
[Discussion] storing the HTML and the content for posts in the database

### ISSUE THREAD

**Issue by MaxLeiter** [MaxLeiter/Drift#74]
Someone hopped in IRC to ask about this and left before I could answer, so thought I'd leave this here in case they or anyone else wants to comment.

At the moment, Drift stores the generated HTML (from markdown) in the Post database model. I figured this was ideal so less logic had to run each time the post was generated/viewed (in case caching isn't setup/failing/not possible). The downsides are database bloat and lack of updates (there's no versioning, so if the HTML parser is updated old posts will not be). The second point can be fixed by adding a version column, but I'm not sure about the DB bloat (but I'm also unsure that's a problem initially)

**Comment by jazcarate** [comment]
~'tis was me 😅 sorry. I forgot I left the IRC.~

After some though, and reading the README.md **TODOs**, where one point states:
> works enough with JavaScript disabled

Maybe we are ok with bloat 😸. 


Either way, I'd rather close this one ticket with "we are ok at the moment" and revisit the issue if/when needed ([YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it))


**Note**: The "version column" you mention might not even be needed, as with each update to the parser, we can also run a migration to re-render from the original text 🤷
