### ISSUE TITLE
Cleanup formatting button component code

### ISSUE THREAD

**Issue by MaxLeiter** [MaxLeiter/Drift#9]
... it's not pretty.

**Comment by lordvins226** [comment]
can you provide more details ?

**Comment by MaxLeiter** [comment]
The file is here: https://github.com/MaxLeiter/Drift/blob/main/client/components/document/formatting-icons/index.tsx

You can see a lot of code is repeated

**Comment by lordvins226** [comment]
I will take a look

**Comment by MaxLeiter** [comment]
closed by f510813
